[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer',
    'php82Extensions.zip',
    'php82Extensions.gd',
    'php82Extensions.mbstring',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.curl',
    'php82Extensions.openssl',
    'php82Extensions.tokenizer',
    'php82Extensions.fileinfo',
    'php82Extensions.xml',
    'nodejs_20'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-req=ext-zip'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear'
]

[start]
cmd = 'bash railway-startup.sh'