[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear'
]

[start]
cmd = 'bash railway-startup.sh'